site_name: Pets Off Road

nav:
- Início: index.md
- Visão: doc_visao.md
- Comunicação: doc_Comunicacao.md
- Apresentações: 
    - Unidade 1: apresentacoes/unidade_01.md
    - Unidade 2: apresentacoes/unidade_02.md
- Políticas do Repositório: 
    - Como contribuir: contributing.md
- Workshop: workshop.md
- Canvas MVP: canvas.md
- Kanban: kanban.md
- SAFe - Backlog: backlog.md

theme: 
  name: material

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde